name: Run Pytest on Push & Pull Request

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv and pytest
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
      - run: uv pip install --system pytest

      - name: Run pytest
        run: pytest ./hash_map/tests/test_lc1_two_sum.py
